version: '3.7'

#
# Variables are loaded from .env file in this folder.
#

services:

  # Nginx container
  nginx:
    image: nginx:1.17-alpine
    container_name: "${PROJECT_NAME}-nginx"
    restart: always
    volumes:
      - ./nginx/includes/cache.conf:/etc/nginx/includes/cache.conf
      - ./nginx/includes/php.conf:/etc/nginx/includes/php.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - "${APP1_PATH}:/app"
    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: "Host:${APP1_HOST}"
    networks:
      - dev-network
      - internal

  #
  # PHP-FPM
  #

  php-fpm:
    image: php:7.3-fpm-alpine
    container_name: "${PROJECT_NAME}-php-fpm"
    restart: always
    volumes:
      - "${APP1_PATH}:/app"
    networks:
      - internal

networks:

  # Network from druidfi/stonehenge
  dev-network:
    name: stonehenge-network
    external: true

  # Internal network for project containers
  internal:
    external: false
