version: '3.6'

#
# SERVICES
#

#
# Variables are loaded from .env file in this folder.
#

services:

  # NGINX

  nginx:
    image: nginx:1.13-alpine
    container_name: "${PROJECT_NAME}-nginx"
    restart: always
    volumes:
      - ./nginx/includes/cache.conf:/etc/nginx/includes/cache.conf
      - ./nginx/includes/php.conf:/etc/nginx/includes/php.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - "${APP1_PATH}:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${PROJECT_NAME}-nginx"
      - "traefik.port=80"
      - "traefik.docker.network=druidfi-network"
      - "traefik.frontend.rule=Host:${APP1_HOST}"
    networks:
      - druidfi-network
      - internal

  #
  # CLI CONTAINER. For using Composer and bin/console
  #

  cli:
    image: druidfi/docker-cli:latest
    container_name: "${PROJECT_NAME}-cli"
    restart: on-failure
    tty: true
    stdin_open: true
    volumes:
      - "${APP1_PATH}:/app"
    networks:
      - internal

  #
  # PHP-FPM
  #

  php-fpm:
    image: php:7.2-fpm-alpine
    container_name: "${PROJECT_NAME}-php-fpm"
    restart: always
    volumes:
      - "${APP1_PATH}:/app"
    networks:
      - internal

#
# VOLUMES
#

volumes:
  mongodb:

networks:
  # Internal network for project containers
  internal:
    external: false

  # Network from druidfi/stonehenge
  druidfi-network:
    external: true
