matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    services: docker
  - os: osx
    osx_image: xcode9.4

env:
  global:
    - DOCKER_COMPOSE_REPO=https://github.com/docker/compose
    - DOCKER_COMPOSE_VERSION=1.22.0
    - STONEHENGE_NETWORK_NAME=stonehenge-network

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh
