sudo: required

language: ruby
services: docker

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode9.4

env:
  global:
    - DOCKER_COMPOSE_REPO=https://github.com/docker/compose
    - DOCKER_COMPOSE_VERSION=1.22.0
    - STONEHENGE_NETWORK_NAME=stonehenge-network

install:
  - ./.travis/install.sh

script:
  - make -v
  - docker --version
  - docker-compose --version
  - docker network create ${STONEHENGE_NETWORK_NAME}
  - docker-compose up -d
  - docker-compose ps
#  - make up
#  - make status
