version: '3.7'

services:
  dnsmasq:
    image: andyshinn/dnsmasq:2.78
    container_name: "${PREFIX}-dnsmasq"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    command: "--address=/.${DOCKER_DOMAIN}/127.0.0.1"
    dns:
      - 1.1.1.1 # Cloudflare
      - 8.8.4.4 # Google
      - 8.8.8.8 # Google
    ports:
      # Bind to non 0.0.0.0 port on ubuntu to prevent port conflict with
      # systemd-resolved.
      - "127.0.0.48:53:53/tcp"
      - "127.0.0.48:53:53/udp"
