version: '3.2'

services:
  dnsmasq:
    ports:
      # Bind to non 0.0.0.0 port on ubuntu to prevent port conflict with
      # systemd-resolved.
      - "127.0.0.48:53:53/tcp"
      - "127.0.0.48:53:53/udp"
