version: '3.7'

#
# Variables are loaded from .env file in this folder.
#

services:

  app:
    image: nginx:1.17-alpine
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/includes/cache.conf:/etc/nginx/includes/cache.conf
      - ./nginx/includes/php.conf:/etc/nginx/includes/php.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - "${APP_PATH}:/app"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.docker.network=stonehenge-network"
    networks:
      - default
      - stonehenge-network

  php-fpm:
    image: php:7.4-fpm-alpine
    container_name: "${COMPOSE_PROJECT_NAME}-php-fpm"
    volumes:
      - "${APP_PATH}:/app"

networks:

  default:
    internal: true

  # Network from druidfi/stonehenge
  stonehenge-network:
    name: "stonehenge-network"
    external: true
