version: '3.7'

#
# Variables are loaded from .env file in this folder.
#

services:

  app:
    image: wordpress:latest
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.docker.network=stonehenge-network"
    networks:
      - default
      - stonehenge-network

  db:
    image: mysql:5.7
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

networks:

  default:
    internal: true

  # Network from druidfi/stonehenge
  stonehenge-network:
    name: stonehenge-network
    external: true

volumes:
  db_data:
