version: '3.7'

#
# Variables are loaded from .env file in this folder.
#

services:

  # Database container
  db:
    image: mysql:8
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - internal

  # Wordpress container
  wordpress:
    depends_on:
    - db
    image: wordpress:latest
    container_name: "${PROJECT_NAME}-wordpress"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: "Host:${APP1_HOST}"
    networks:
    - dev-network
    - internal

networks:

  # Network from druidfi/stonehenge
  dev-network:
    name: stonehenge-network
    external: true

  # Internal network for project containers
  internal:
    external: false

volumes:
  db_data:
