version: '3.2'

#
# SERVICES
#

#
# Variables are loaded from .env file in this folder.
#

services:

  # Contenta CMS

  contentacms:
    image: druidfi/docker-drupal:php71-basic
    container_name: "${PROJECT_NAME}-contentacms"
    restart: always
    hostname: &hostname ${APP1_HOST}
    environment:
      VIRTUAL_HOST: *hostname
      WEBROOT: web
    volumes:
      - ./contentacms:/var/www/drupal/public_html:delegated
    labels:
      traefik.enable: true
      traefik.backend: "${PROJECT_NAME}-contentacms"
      traefik.port: 80
      traefik.docker.network: stonehenge-network
      traefik.frontend.rule: "Host:${APP1_HOST}"
    networks:
      - stonehenge-network
      - internal

#
# VOLUMES
#

volumes: {}

#
# NETWORKS
#

networks:
  # Internal network for project containers
  internal:
    external: false

  # Network from druidfi/stonehenge
  stonehenge-network:
    external: true
