version: '3.7'

#
# Variables are loaded from .env file in this folder.
#

services:

  # Contenta CMS container
  contentacms:
    image: druidfi/docker-drupal:php71-basic
    container_name: "${PROJECT_NAME}-contentacms"
    hostname: &hostname ${APP1_HOST}
    environment:
      VIRTUAL_HOST: *hostname
      WEBROOT: web
      # Site URI for Drush 9
      DRUSH_OPTIONS_URI: *hostname
    volumes:
      - ./contentacms:/var/www/drupal/public_html:delegated
      - ssh:/tmp/amazeeio_ssh-agent:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:${APP1_HOST}"
    networks:
      - dev-network

networks:

  # Network from druidfi/stonehenge
  dev-network:
    name: stonehenge-network
    external: true

volumes:

  # Volume from druidfi/stonehenge
  ssh:
    name: stonehenge-ssh
    external: true
