version: '3.6'

#
# SERVICES
#

#
# Variables are loaded from .env file in this folder.
#

services:

  #
  # GHOST
  #

  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${PROJECT_NAME}-ghost"
      - "traefik.port=2368"
      - "traefik.docker.network=stonehenge-network"
      - "traefik.frontend.rule=Host:${APP1_HOST}"
    networks:
      - internal
      - stonehenge-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - internal

#
# VOLUMES
#

volumes: {}

#
# NETWORKS
#

networks:
  # Internal network for project containers
  internal:
    external: false

  # Network from druidfi/stonehenge
  stonehenge-network:
    external: true
