version: '3.7'

#
# Variables are loaded from .env file in this folder.
#

services:

  app:
    image: ghost:3-alpine
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    depends_on:
      - db
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
      url: https://${APP_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=2368"
      - "traefik.docker.network=stonehenge-network"
    networks:
      - default
      - stonehenge-network

  db:
    image: mysql:5.7
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    environment:
      MYSQL_ROOT_PASSWORD: someghost
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost

networks:

  default:
    internal: true

  # Network from druidfi/stonehenge
  stonehenge-network:
    name: "stonehenge-network"
    external: true
