version: '3.7'

#
# Variables are loaded from .env file in this folder.
#

services:

  # Ghost container
  ghost:
    image: ghost:2-alpine
    container_name: "${PROJECT_NAME}-ghost"
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: https://${APP1_HOST}
    labels:
      traefik.enable: true
      traefik.port: 2368
      traefik.frontend.rule: "Host:${APP1_HOST}"
    networks:
      - default
      - dev-network

  # Database container
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - default

networks:

  # Network from druidfi/stonehenge
  dev-network:
    name: stonehenge-network
    external: true
