version: '3.7'

#
# Variables are loaded from .env file in this folder.
#

services:

  # Hugo container
  hugo:
    image: klakegg/hugo:0.58.3
    command: "server --appendPort=false --baseUrl=${APP1_HOST} -D"
    volumes:
    - ./site:/src
    ports:
    - 1313:1313
    restart: always
    environment:
      HUGO_ENV: DEV
    labels:
      traefik.enable: true
      traefik.port: 1313
      traefik.frontend.rule: "Host:${APP1_HOST}"
    networks:
      - internal
      - dev-network

networks:

  # Network from druidfi/stonehenge
  dev-network:
    name: stonehenge-network
    external: true

  # Internal network for project containers
  internal:
    external: false
