name: Tests

on: [push]

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        #os: [ ubuntu-latest, macos-latest ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Show debug info
        run: |
          docker --version
          docker-compose --version
          make debug
          make ping

      - name: Start up Stonehenge
        run: make up

      - name: Ping should resolve to 127.0.0.1 now
        run: make ping

      - name: Check that DNS works when curling Google. Expecting HTTP/2 200
        run: curl -Is https://www.google.com | head -1
