name: Tests

on: [push]

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Show make version
        run: make --version

      - name: Show docker version
        run: docker --version

      - name: Show docker-compose version
        run: docker-compose --version
